### ISSUE TITLE
Question: python render.py crashes

### ISSUE THREAD

**Issue by t4sk** [lightninglabs/lightning-api#1]
`ruby 2.4.2`
`firefox 56 (linux)`

`python render.py` crashes because `rpc.json` that I have is different from what `render.py` expects. 

```
Traceback (most recent call last):
  File "render.py", line 393, in <module>
    render()
  File "render.py", line 352, in render
    rpc_methods = json_proto_to_rpc_dict()
  File "render.py", line 129, in json_proto_to_rpc_dict
    file_services = data[0]['file_services']
KeyError: 0
```

 By changing the keys in `render.py`, I was able to regenerate the document.

Should I create a pull request?

**Comment by MaxFangX** [comment]
We can handle the rendering and updating the site, no need to worry about it.
