### ISSUE TITLE
Feature: make it clear which fields are required, which fields are optional, which are alternative.

### ISSUE THREAD

**Issue by marsrobertson** [lightninglabs/lightning-api#11]
* Some fields are required.
* Some fields are optional.
* Some fields are alternative, for example, if the whole invoice is specified, other fields are duplicate, confusing, alternative.
```
var requestBody = { 
  payment_request: "lnbc100n1.........",
};
```

I tried making sense what `*` or `/` mean but it’s unclear which is which.

https://api.lightning.community/rest/?javascript#v1-invoices

![image](https://user-images.githubusercontent.com/44369284/58764590-cfbaef00-8560-11e9-963f-779d030f11e6.png)

_(I'm sorry, too busy, didn't have time to check `dev` branch)_

**Comment by guggero** [comment]
The characters `*` and `/` were a left over artifact of how the comments were added to the `proto` files and were not supposed to be visible in the docs. We fixed that part a while ago.

The API doc is auto generated. And on the level of the document generation we don't have the information about which parameter is required or not. The best hint is the description itself.
