### ISSUE TITLE
Please specify in the README what this project is based on/forked from

### ISSUE THREAD

**Issue by stevenroose** [lightninglabs/lightning-api#2]
I can't seem to find it..

**Comment by stevenroose** [comment]
Found it here: https://github.com/lightninglabs/lightning-api/blob/134454fc7a7986775bfa84708e2a245ec540438b/README.md

**Comment by MaxFangX** [comment]
Hi Steven - Slate is currently specified in the [README](https://github.com/lightninglabs/lightning-api/blob/master/README.md) and is mentioned repeatedly.. Closing this for now unless you still think something needs to change.

**Comment by stevenroose** [comment]
Missed that, I'm sorry.
